<?php
/**
 * P7: unique 200-300 word body copy per topic_category, keyed by slug.
 * Replaces the old identical "About Our X Coloring Pages" boilerplate
 * that was the same two sentences on every category archive page.
 */
return array(
	'animals' => "Our Animals collection is built for kids who light up at the sight of a lion, a giraffe, or a puppy — roughly ages 3 to 10, from a toddler's first crayon scribbles to an early-elementary student practicing careful outlines. Parents often reach for these pages during quiet time or right after a trip to the zoo or aquarium, using the picture as a jumping-off point for conversation: what does a shark eat, why does a giraffe have a long neck, what sound does a rooster make. Teachers lean on the same pages for animal-themed units, letter-sound lessons (D is for Dog), and calm-down corners where a five-minute coloring break resets a busy classroom.\n\nThe set covers over 50 animals, from everyday pets like Cat and Dog to farm animals, safari favorites like Lion and Elephant, and ocean life like Shark and Octopus, so there's almost always a match for whatever a child is currently curious about. Every page is free to download as a print-ready PDF or PNG, sized for both US Letter and A4 paper, so it prints cleanly whether you're at home, in a US classroom, or in a school abroad.\n\nIf your child has worked through their favorite animals here, our Nature collection pairs naturally with outdoor and habitat themes, and Fantasy & Cute offers a gentler, more whimsical companion for kids who enjoy imaginative creatures alongside the real ones.",

	'fantasy-cute' => "Fantasy & Cute is where imaginative kids go to color unicorns, dragons, fairies, mermaids, and friendly robot characters — a favorite with children roughly 3 to 10 who love make-believe as much as they love markers. Parents often use these pages as a bedtime wind-down activity or a rainy-afternoon project, letting a child invent a name and a backstory for the creature before the crayons even come out. Teachers use the same pages as creative-writing prompts (\"What does this dragon like to eat for breakfast?\") or as a reward activity after a focused work block.\n\nThe collection includes classic favorites like Unicorn, Dragon, Fairy, Mermaid, and Princess alongside original characters like Hero Robot and Ranger Squad Hero, so kids who love traditional fantasy and kids who love superheroes both find something to color. Every illustration keeps bold, simple outlines and generous open space, which matters more here than in most categories since fantasy art can easily get too detailed for small hands — we deliberately keep the linework kid-friendly. Pages download as free, print-ready PDFs or PNGs in both US Letter and A4 sizes, so there's no sign-up or payment needed before you print.\n\nFor families who enjoy this style, our People & Jobs pages offer a similar character-driven format grounded in real-world roles like firefighter and astronaut, while Animals gives the same warm, expressive faces on real-world creatures.",

	'educational' => "The Educational collection turns core preschool and kindergarten skills — letters, numbers, shapes, days of the week, seasons, opposites, and more — into a coloring activity instead of a worksheet, which is exactly why parents and teachers reach for it so often. A parent working on letter recognition at home can pair a coloring page with the matching flashcard; a kindergarten teacher can hand out the Number 7 page during a counting lesson and get quiet, focused practice time without losing the learning goal. Because each page keeps one concept large and centered on the page, even a child who isn't reading yet can recognize what they're looking at.\n\nTopics range from the full Alphabet and Numbers 1 through 12 to Shapes, Days of the Week, Seasons, an Opposites chart, and a Weather chart with sun and rain — the kind of foundational content homeschool parents and classroom teachers both build lesson plans around. Every page is a free, print-ready PDF or PNG sized for US Letter or A4 paper, so it's easy to print a full set for a classroom or just the next letter your child is learning at home.\n\nBecause early-learning skills show up everywhere, this category pairs naturally with almost anything else on the site — many families combine an Educational page with a themed one from Animals or Vehicles to reinforce a letter or number while keeping the subject matter fun.",

	'food' => "Kids are naturally drawn to food they recognize, and this collection — pizza, ice cream, birthday cake, fruits, vegetables, donuts, cupcakes, and more — gives them a coloring page that doubles as a conversation about healthy eating, kitchen play, or an upcoming celebration. Parents often bring these out around mealtime or a birthday to get a picky eater talking about food in a low-pressure way, while preschool and elementary teachers use them for nutrition units, sorting healthy versus treat foods, or as a simple center-time activity that doesn't need much setup.\n\nThe set spans everyday basics like Fruits and Vegetables through classic treats like Ice Cream, Birthday Cake, and Pizza, plus detailed favorites like a Glazed Donut with Sprinkles, a Frosted Cupcake with a Cherry, and a Chocolate Chip Cookie — enough variety that a themed birthday party or a weekly \"food of the day\" classroom activity can pull a fresh page every time. As with every category on the site, each page is a free, original illustration you can download as a print-ready PDF or PNG in US Letter or A4, ready for crayons, markers, or colored pencils.\n\nFood pages are a natural pairing with our Seasonal collection for holiday treats, and with Educational for counting and sorting activities built around fruits, vegetables, and snacks.",

	'nature' => "The Nature collection — flowers, trees, sun and clouds, rainbows, gardens, ocean waves, sandy beaches, and mountain peaks — is a favorite for calm, unhurried coloring time, especially after a walk outside or a trip to the park. Parents use these pages to extend a nature walk indoors, asking a child to color the flowers they remember seeing or the clouds they watched drift by, while teachers reach for them during science and weather units, Earth Day activities, or simply as a peaceful transition activity between lessons.\n\nBecause the subjects are simple, familiar shapes — a sun, a tree, a wave — these pages tend to work well for younger toddlers just starting to hold a crayon, while the more detailed scenes like Sandy Beach with a Beach Ball or Mountain Peak give older kids more to work with. Every page is a free, original illustration available as a print-ready PDF or PNG sized for US Letter or A4 paper, so it's simple to build a full nature-themed packet for a classroom or homeschool unit.\n\nNature pairs naturally with our Seasonal collection, since weather and outdoor scenes shift with the time of year, and with Animals for kids who want to color the creatures that live in the gardens, oceans, and mountains they're already coloring.",

	'people-jobs' => "Kids go through an age — usually somewhere around 3 to 8 — where they're endlessly curious about what grown-ups actually do all day, and this collection of firefighters, doctors, astronauts, police officers, teachers, and more gives that curiosity somewhere to go. Parents use these pages to talk through community helpers and future-career daydreams (\"Do you want to be an astronaut like this one?\"), while teachers lean on the same set for community-helper units, career day, and social studies lessons that introduce real jobs in a friendly, approachable way.\n\nAlongside the everyday roles like Firefighter, Doctor, Police Officer, and Teacher, the set also includes a few more playful characters like Ninja Kid, Rescue Pup, and Pirate Captain, so kids who gravitate toward imaginative role-play have just as much to color as kids interested in real-world careers. Every page is a free, print-ready download available as a PDF or PNG in US Letter or A4, so a teacher can print a full set for a career-day bulletin board just as easily as a parent can print one page for an afternoon activity.\n\nThis category pairs well with Vehicles for job-specific equipment like fire trucks and police cars, and with Fantasy & Cute for kids who enjoy the same expressive, character-driven art style in a more imaginative setting.",

	'seasonal' => "The Seasonal collection follows the calendar year — Spring, Summer, Autumn, Winter, a classic Snowman, Back to School in Autumn, Spring Cleaning, and Summer Vacation — so there's almost always a page that matches whatever season a family or classroom is currently in. Parents often rotate these pages in as decorations or quiet activities as the weather changes, while teachers use them to mark transitions in the school year, from a Back to School scene in late summer to a Winter unit before the holidays.\n\nBecause the theme is tied to real seasonal change kids experience firsthand — falling leaves, the first snow, packing a suitcase for summer vacation — these pages tend to spark easy conversation about what a child notices happening outside their own window. Every illustration is a free, original design available as a print-ready PDF or PNG in US Letter or A4, so it's simple to swap in a new page every few months without any cost or sign-up.\n\nSeasonal pairs naturally with our Holidays collection for the celebrations that fall within each season, and with Nature for the outdoor scenery — sun, snow, gardens, and more — that changes right alongside it. Many homeschool families work through the set page by page as a light, low-pressure way to talk about the calendar and the weather throughout the year.",

	'sports-activities' => "For kids who would rather be moving than sitting still, this collection gives them a coloring page about the sports and activities they already love — soccer, basketball, swimming, dancing, bicycles, baseball, football, and tennis. Parents often use these pages to celebrate a favorite sport or a big game day, while PE teachers and classroom teachers alike use them as a calm indoor activity on a rainy day when the usual outdoor activity time isn't possible.\n\nThe set includes both simple, single-subject pages like Soccer and Basketball and more detailed action scenes like Kid Playing Baseball with a Bat, Kid Playing Football with a Football, and Kid Playing Tennis with a Racket, giving younger children an easy shape to color and older kids more detail to work through. As with every collection on the site, each page is a free, original illustration you can download as a print-ready PDF or PNG in US Letter or A4, ready to print at home, in a classroom, or for an after-school sports program.\n\nSports & Activities pairs naturally with People & Jobs for kids interested in coaches and athletes as career role models, and with Seasonal for sports tied to a particular time of year.",

	'vehicles' => "Cars, trucks, airplanes, trains, and fire trucks are a near-universal favorite with young kids, and this collection gives them a full garage's worth of vehicles to color, from everyday favorites like Car and Truck to exciting ones like Fire Truck, Monster Truck, and Motorcycle. Parents often use these pages during car rides, waiting rooms, or any moment they need a quiet, engaging activity on hand, while teachers use them for transportation units, letter-sound lessons (T is for Truck), and classroom centers built around how things move.\n\nBecause vehicles are such concrete, recognizable shapes, these pages work well across a wide age range — a toddler can recognize and name the vehicle before they're old enough to color inside the lines, while an older child can talk through how each vehicle is used, from a Sky Squad Plane in the air to a Fire Truck racing to help. Every page is a free, original illustration available as a print-ready PDF or PNG sized for US Letter or A4 paper, so there's no cost or account needed before you print.\n\nVehicles pairs naturally with People & Jobs for the drivers, pilots, and firefighters who operate them, and with Educational for counting and sorting activities built around wheels, colors, and vehicle types.",

	'holidays' => "The Holidays collection covers the celebrations families look forward to all year — Christmas, Halloween, Easter, Thanksgiving, Valentine's Day, New Year's Eve, St. Patrick's Day, and the Fourth of July, among others — giving parents and teachers a ready-made activity for nearly every holiday on the calendar. Parents use these pages to keep kids occupied and excited in the lead-up to a holiday, whether that's coloring a Christmas scene while waiting for cookies to bake or a Halloween page before trick-or-treating, while teachers use the same pages for classroom parties, holiday bulletin boards, and seasonal craft time.\n\nBeyond the major holidays, the set also includes smaller, often-overlooked celebrations like New Year's Eve Fireworks and Countdown Clock, St. Patrick's Day Shamrock and Pot of Gold, and Fourth of July Fireworks, so there's a page ready even for the holidays that don't usually get their own worksheet. Every illustration is a free, original design available as a print-ready PDF or PNG in US Letter or A4, so a classroom can print a full set for a holiday party without any cost or sign-up.\n\nHolidays pairs closely with our Seasonal collection, since most major holidays fall within a specific season, and with Food for the treats — cookies, candy, cake — that traditionally go along with each celebration.",
);
